SELECT * FROM tbl;
-- Should just show the table struct with the name of the table
--
-- Perhaps something like this
--
--       _____
--       |All|
--       -----
--         |
--       _____
--       |tbl|
--       -----
